version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - ZachTRice
  - Benjaki2
  ignore:
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.1
  - dependency-name: web-streams-polyfill
    versions:
    - 3.0.1
    - 3.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: eslint-config-node
    versions:
    - 4.1.0
